# Generated by Django 4.0.6 on 2022-07-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_rating'),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='foods.category'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ManyToManyField(related_name='location', to='restaurant.restaurant'),
        ),
    ]
